[package]
name = "sage-cloudpath"
version = "0.9.0"
authors = ["Michael Lazear <michaellazear92@gmail.com"]
edition = "2021"
rust-version = "1.62"
description = "A very fast proteomics database search tool"
readme = "README.md"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sage-core = { path = "../sage" }
async-compression = { version = "0.3", features = ["tokio", "gzip"] }
aws-config = "0.49"
aws-sdk-s3 = "0.19"
bytes = "1.0"
http = "0.2"
once_cell = "1.0"
tokio = { version = "1.0", features = ["fs", "io-util", "rt"] }